name: Compile and release my business card 
on : 
  push:
    tags:
      - '*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name : Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: card.tex
        # Working directory for the compilation process
          working_directory: /Users/leonorejamet/Documents/MasterDataScience/RefresherCS/my-business-card
        # Use XeLaTeX engine with latexmk
          latexmk_use_xelatex: true
